# Generated by Django 2.1.1 on 2018-11-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product', verbose_name='Imagem')),
                ('small', models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Small')),
            ],
            options={
                'verbose_name': 'Imagem',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
